In [10]:
import requests
import pandas as pd

# Tail numbers for tracking
tail_numbers = ["N350XX", "N621MM", "TAY8AN"]

def get_flight_info(tail_numbers):
    """Fetch last known location and flight details for private jets."""

    url = "https://opensky-network.org/api/states/all"  # OpenSky API Endpoint
    response = requests.get(url).json()

    # Create a list to store flight details
    flight_data = []

    # Loop through each aircraft in the response
    for aircraft in response["states"]:
        callsign = aircraft[1].strip() if aircraft[1] else "N/A"
        icao24 = aircraft[0]  # Unique aircraft identifier
        lat, lon, altitude, velocity = aircraft[6], aircraft[5], aircraft[7], aircraft[9]

        # Check if aircraft matches our target tail numbers
        for tail in tail_numbers:
            if callsign == tail:
                flight_data.append({
                    "Aircraft": tail,
                    "Latitude": lat,
                    "Longitude": lon,
                    "Altitude (meters)": altitude,
                    "Speed (m/s)": velocity,
                    "ICAO24": icao24
                })

    # Convert to Pandas DataFrame and display results
    df = pd.DataFrame(flight_data)

    if df.empty:
        print("No matching flights found. Aircraft may be grounded.")
    else:
        print("\nFlight Information:")
        display(df)  # Works in Google Colab

# Run the function
get_flight_info(tail_numbers)

Flight Information:

  Aircraft  Latitude  Longitude  Altitude (meters)  Speed (m/s)  ICAO24
0   TAY8AN   50.6422     1.1138             8534.4        181.1  440af5